test with fake db

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -6,6 +6,7 @@ on:
     paths:
       - "frontend/**"
       - "api/**"
+      - "db/**"
 
 jobs:
   frontend:
@@ -53,3 +54,16 @@ jobs:
 
       - name: Build
         run: npm run build --if-present
+
+  db:
+    runs-on: ubuntu-latest
+    defaults:
+      run:
+        working-directory: db
+    steps:
+      - uses: actions/checkout@v4
+      - name: Show files
+        run: |
+          pwd
+          ls -la
+          test -f init.sql && echo "init.sql found ✅" || (echo "init.sql missing ❌" && exit 1)
